<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <!DOCTYPE html>
<html lang="pt">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Bem vindo</title>


    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

 
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


    <link href="css/clean-blog.min.css" rel="stylesheet">

  </head>

  <body>


    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="http://localhost/SistemaCandidato/index.php">Pagina inicial</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="http://localhost/SistemaCandidato/Empresa/listar.php">Ver sua conta</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost/SistemaCandidato/vagas/form_inserir.php">Cadastro de vagas</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="http://localhost/SistemaCandidato/login/logout.php">Sair</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://localhost/SistemaCandidato/Entrevistas/listarPossiveis.php">Cadastrar entrevistas</a>
            </li>
             
          </ul>
        </div>
      </div>
    </nav>
  </body>
    <header class="masthead" style="background-image: url('./img/about-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
          
          </div>
        </div>
      </div
      </div>
    </header>
    </body>
</html>
